Sisteminha4/config/routes.rb
Sisteminha2::Application.routes.draw do

  root :to => 'static#index'
  
  
  get 'static/:id' => 'static#static', :as => :static
  
  
  match '/nota_vt/incluir_operacoes_com_vagoes', :controller => 'nota_vts', :action => :incluirOperacoesComVagoes
  
  match '/composicao_de_vagao/atualizar_vagao_carregado', :controller => 'composicao_de_vagaos', :action => :atualizarVagaoCarregado
  
  match '/composicao_de_vagao/atualizar_vagoes_carregados', :controller => 'composicao_de_vagaos', :action => :atualizarVagoesCarregados
  
  match '/composicao_de_vagao/aceitar_atualizacao_vagoes_carregados', :controller => 'composicao_de_vagaos', :action => :atualizacaoVagoesCarregadosAceita
  
  
  match 'relatorios/gerar_relatorio_de_amostras', :controller => :relatorios, :action => :gerarRelatorioAmostras
  
  match 'relatorios/gerar_relatorio_tempos_composicoes_vagoes', :controller => :relatorios, :action => :gerar_relatorio_tempos_composicoes_vagoes
  
  match 'relatorios/gerar_relatorio_fechamento_diario_vagoes', :controller => :relatorios, :action => :gerar_relatorio_fechamento_diario_vagoes
  
  match 'relatorios', :controller => :relatorios, :action => :index
  
  match 'menu_vt', :controller => :vts, :action => :menu_vt
  
  match 'amostras_navio/new', :controller => :amostras_navio, :action => :new
  
  match 'amostras_navio/create', :controller => :amostras_navio, :action => :create
  
  match 'buscar_amostras', :controller => :amostras, :action => :index
  
  match 'buscar_operacoes_com_vagoes', :controller => :operacao_com_vagaos, :action => :index
  
  match '/buscar_notas_de_vts', :controller => :nota_vts, :action => :index
  
  match '/conjunto_operacoes_de_vagoes/create', :controller => :conjunto_operacoes_de_vagoes, :action => :create
  
  match '/conjunto_operacoes_de_vagoes/confirmar_produto', :controller => :conjunto_operacoes_de_vagoes, :action => :confirmarProduto
  
  match '/conjunto_operacoes_de_vagoes/atualizar_operacoes', :controller => :conjunto_operacoes_de_vagoes, :action => :atualizarOperacoes
  
  match '/conjunto_operacoes_de_vagoes/confirmar_atualizacao_operacoes', :controller => :conjunto_operacoes_de_vagoes, :action => :confirmarAtualizacaoOperacoes

  match '/operacao_com_vagao/limpar_composicao', :controller => :operacao_com_vagaos, :action => :limparComposicao
  
  resources :fechamento_diario_vagaos

  resources :composicao_de_vagaos

  resources :lacres

  resources :solicitacaos

  resources :vts

  resources :vistorias

  resources :usuarios

  resources :tipo_amostras

  resources :produto_vts

  resources :produtos

  resources :problemas

  resources :origems

  resources :operacao_com_vagaos

  resources :operacaos

  resources :nota_vts

  resources :grupo_usuarios

  resources :finalidades

  resources :amostras
  
  get ":id" => "static#static", :as => :static

end

Sisteminha4/app/models/vistoria.rb
# encoding: utf-8
class Vistoria < ActiveRecord::Base

  validates_presence_of :data, :vt
  validate :dataVistoriaValidates

  belongs_to :vt

  has_and_belongs_to_many :problemas
  
  def dataVistoriaValidates
    vistoria = Vt.find(self.vt).vistorias.last
    if self.data != nil and vistoria != nil and vistoria.data > self.data
      self.errors.add :data, "deve ser posterior ou igual a data da última vistoria deste vagão."
    end
    if vistoria != nil and vistoria.id != self.id and  self.id != nil
      self.errors.add :id, ": Você só pode alterar a última vistoria deste vagão."
    end
  end
end

Sisteminha4/app/controllers/vistorias_controller.rb
class VistoriasController < ApplicationController
  
  before_filter :liberarAcesso, :except => [:index, :show, :new]
  def liberarAcesso
    if @usuario.privilegio.id == 2
    return true
    else
      redirect_to "/static/grupo_diferente"
    return false
    end
  end
  
  
  # GET /vistorias
  # GET /vistorias.json
  def index
    @vistorias = Vistoria.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vistorias }
    end
  end

  # GET /vistorias/1
  # GET /vistorias/1.json
  def show
    @vistoria = Vistoria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vistoria }
    end
  end

  # GET /vistorias/new
  # GET /vistorias/new.json
  def new
    @vistoria = Vistoria.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vistoria }
    end
  end

  # GET /vistorias/1/edit
  def edit
    @vistoria = Vistoria.find(params[:id])
  end

  # POST /vistorias
  # POST /vistorias.json
  def create
    @vistoria = Vistoria.new(params[:vistoria])

    respond_to do |format|
      if @vistoria.save
        format.html { redirect_to @vistoria, notice: 'Vistoria criada com sucesso.' }
        format.json { render json: @vistoria, status: :created, location: @vistoria }
      else
        format.html { render action: "new" }
        format.json { render json: @vistoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vistorias/1
  # PUT /vistorias/1.json
  def update
    @vistoria = Vistoria.find(params[:id])

    respond_to do |format|
      if @vistoria.update_attributes(params[:vistoria])
        format.html { redirect_to @vistoria, notice: 'Vistoria atualizada com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @vistoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vistorias/1
  # DELETE /vistorias/1.json
  def destroy
    @vistoria = Vistoria.find(params[:id])
    @vistoria.destroy

    respond_to do |format|
      format.html { redirect_to vistorias_url }
      format.json { head :ok }
    end
  end
end

Sisteminha4/app/helpers/vistorias_helper.rb
module VistoriasHelper
end

Sisteminha4/app/views/vistorias/_form.html.erb
<%= form_for(@vistoria) do |f| %>
<% if @vistoria.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@vistoria.errors.count, "erro proíbe") %> esta vistoria de ser salva:</h2>
	<ul>
		<% @vistoria.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<%= f.label :data %>
	<br />
	<%= f.text_field :data, :value => formatarData(@vistoria.data) %>
</div>
<% if @vistoria.vt == nil %>
<div class="field">
	<%= f.label :vt %>
	<br />
	<%= f.collection_select(:vt_id, Vt.all.sort_by{|vt| [vt.numero_curto]}, :id, :numero_curto) %>
</div>
<%else%>
<div class="field">
	<%= f.label :vt %>
	<br />
	<%= @vistoria.vt.numero_curto %>
	<%= f.hidden_field :vt_id, :value => @vistoria.vt.id %>
</div>
<%end%>
<div class="field">
	<%= f.label :problemas %>
	<br />
	<% Problema.all.each do |problema| %>
	<li>
		<%= check_box_tag :problema_ids, problema.id, @vistoria.problemas.include?(problema), :name => 'vistoria[problema_ids][]' %>
		<%= label_tag :problema_ids, problema.descricao %>
	</li>
	<% end %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %> 

Sisteminha4/app/views/vistorias/_menu.html.erb
<li>
	<a > <%= link_to 'Incluir Vistoria', new_vistoria_path %> </a>
</li>
<li>
	<a> <%= link_to 'Listar Vistorias', vistorias_path %></a>
</li>

Sisteminha4/app/views/vistorias/_part_index.html.erb
<h1>Vistorias</h1>

<br>
<table cellpadding="0" cellspacing="0" border="0" class="display dataTable" >
	<thead>
		<tr>
			<th>Número</th>
			<th>Data</th>
			<th>Vagão</th>
			<th>Problemas</th>
		</tr>
	</thead>
	<tbody>
		<% @vistorias.each do |vistoria| %>
		<tr>
			<td><%= link_to vistoria.id, vistoria %></td>
			<td><%= formatarData(vistoria.data) %></td>
			<td><%= vistoria.vt.numero_curto %></td>
			<td><% vistoria.problemas.each do |problema| %>
			<%= problema.descricao %>
			<br>
			<% end %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
<br>

Sisteminha4/app/views/vistorias/edit.html.erb
<%= render 'vistorias/menu' %>
<%= render 'layouts/final_menu' %> 
<h1>Editar vistoria</h1>

<%= render 'form' %>

Sisteminha4/app/views/vistorias/index.html.erb
<%= render 'vistorias/menu'%>
<%= render 'layouts/final_menu' %> 
<%= render 'vistorias/part_index'%>

Sisteminha4/app/views/vistorias/new.html.erb
<%= render 'vistorias/menu' %>
<%= render 'layouts/final_menu' %> 
<h1>Nova vistoria</h1>

<%= render 'form' %>

Sisteminha4/app/views/vistorias/show.html.erb
<%= render 'vistorias/menu' %>
<%= render 'layouts/final_menu' %> 
<%= render 'layouts/notificacoes' %> 

<p>
  <b>Data:</b>
  <%= formatarData(@vistoria.data) %>
</p>

<p>
  <b>Vt:</b>
  <%= link_to @vistoria.vt.numero_curto, @vistoria.vt %>
</p>

<%= link_to 'Editar', edit_vistoria_path(@vistoria) %> |
<%= link_to 'Deletar', @vistoria, confirm: 'Você tem certeza?', method: :delete %>

</br>
</br>
<% @problemas = @vistoria.problemas %>
<%= render 'problemas/part_index' %> 