Sisteminha4/config/routes.rb
Sisteminha2::Application.routes.draw do

  root :to => 'static#index'
  
  
  get 'static/:id' => 'static#static', :as => :static
  
  
  match '/nota_vt/incluir_operacoes_com_vagoes', :controller => 'nota_vts', :action => :incluirOperacoesComVagoes
  
  match '/composicao_de_vagao/atualizar_vagao_carregado', :controller => 'composicao_de_vagaos', :action => :atualizarVagaoCarregado
  
  match '/composicao_de_vagao/atualizar_vagoes_carregados', :controller => 'composicao_de_vagaos', :action => :atualizarVagoesCarregados
  
  match '/composicao_de_vagao/aceitar_atualizacao_vagoes_carregados', :controller => 'composicao_de_vagaos', :action => :atualizacaoVagoesCarregadosAceita
  
  
  match 'relatorios/gerar_relatorio_de_amostras', :controller => :relatorios, :action => :gerarRelatorioAmostras
  
  match 'relatorios/gerar_relatorio_tempos_composicoes_vagoes', :controller => :relatorios, :action => :gerar_relatorio_tempos_composicoes_vagoes
  
  match 'relatorios/gerar_relatorio_fechamento_diario_vagoes', :controller => :relatorios, :action => :gerar_relatorio_fechamento_diario_vagoes
  
  match 'relatorios', :controller => :relatorios, :action => :index
  
  match 'menu_vt', :controller => :vts, :action => :menu_vt
  
  match 'amostras_navio/new', :controller => :amostras_navio, :action => :new
  
  match 'amostras_navio/create', :controller => :amostras_navio, :action => :create
  
  match 'buscar_amostras', :controller => :amostras, :action => :index
  
  match 'buscar_operacoes_com_vagoes', :controller => :operacao_com_vagaos, :action => :index
  
  match '/buscar_notas_de_vts', :controller => :nota_vts, :action => :index
  
  match '/conjunto_operacoes_de_vagoes/create', :controller => :conjunto_operacoes_de_vagoes, :action => :create
  
  match '/conjunto_operacoes_de_vagoes/confirmar_produto', :controller => :conjunto_operacoes_de_vagoes, :action => :confirmarProduto
  
  match '/conjunto_operacoes_de_vagoes/atualizar_operacoes', :controller => :conjunto_operacoes_de_vagoes, :action => :atualizarOperacoes
  
  match '/conjunto_operacoes_de_vagoes/confirmar_atualizacao_operacoes', :controller => :conjunto_operacoes_de_vagoes, :action => :confirmarAtualizacaoOperacoes

  match '/operacao_com_vagao/limpar_composicao', :controller => :operacao_com_vagaos, :action => :limparComposicao
  
  resources :fechamento_diario_vagaos

  resources :composicao_de_vagaos

  resources :lacres

  resources :solicitacaos

  resources :vts

  resources :vistorias

  resources :usuarios

  resources :tipo_amostras

  resources :produto_vts

  resources :produtos

  resources :problemas

  resources :origems

  resources :operacao_com_vagaos

  resources :operacaos

  resources :nota_vts

  resources :grupo_usuarios

  resources :finalidades

  resources :amostras
  
  get ":id" => "static#static", :as => :static

end

Sisteminha4/app/models/fechamento_diario_vagao.rb
#encoding: utf-8
class FechamentoDiarioVagao < ActiveRecord::Base
  
  validates :data, :uniqueness =>  true, :presence => true
  validate :validarSeUltimaParaAlterar
  validate :validarPossibilidadeDeAlteracao
  
  has_many :composicao_de_vagaos
  
  def pesoTotal
    p = 0
    composicao_de_vagaos.each do |cv|
      p = p + cv.totalPeso
    end
    p
  end
  
  def qtdOperacoes
    qtd = 0
    composicao_de_vagaos.each do |comp|
      qtd = qtd + comp.operacao_com_vagaos.length
    end
    qtd
  end
  
  def produto
    produtos = []
    string = ''
    composicao_de_vagaos.each do |comp|
      if !produtos.include?(comp.produto)
        produtos << comp.produto
        string = "#{string} #{comp.produto}"
      end
    end
    string
  end
  
  def composicoesFinalizado?
    composicoes_finalizadas = true
    if composicao_de_vagaos == []
      composicoes_finalizadas = false
    end
    composicao_de_vagaos.each do |comp|
      if !comp.operacoesFinalizadas?
      composicoes_finalizadas = false
      break
      end
    end
    composicoes_finalizadas
  end
  
  private 
  
  def validarSeUltimaParaAlterar
    if id != nil
      valido = false
      fechamentos = FechamentoDiarioVagao.last(2)
      fechamentos.each do |f|
        if f.id == id
          valido = true
        end
      end
      if !valido
        errors.add :id, ": Só é permitido alterar os dois últimos fechamentos de vagões."
      end
    end
  end
  
  def validarPossibilidadeDeAlteracao
    if composicoesFinalizado?
      errors.add :id, ": Operação já está finalizada"
    end
  end
  
  public
end

Sisteminha4/app/controllers/fechamento_diario_vagaos_controller.rb
#encoding: utf-8
class FechamentoDiarioVagaosController < ApplicationController
  
  before_filter :liberarAcesso, :except => [:index, :show, :new]
  def liberarAcesso
    if @usuario.privilegio.id == 2
    return true
    else
      redirect_to "/static/grupo_diferente"
    return false
    end
  end
  
  
  # GET /fechamento_diario_vagaos
  # GET /fechamento_diario_vagaos.json
  def index
    @fechamento_diario_vagaos = FechamentoDiarioVagao.last(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fechamento_diario_vagaos }
    end
  end

  # GET /fechamento_diario_vagaos/1
  # GET /fechamento_diario_vagaos/1.json
  def show
    @fechamento_diario_vagao = FechamentoDiarioVagao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fechamento_diario_vagao }
    end
  end

  # GET /fechamento_diario_vagaos/new
  # GET /fechamento_diario_vagaos/new.json
  def new
    @fechamento_diario_vagao = FechamentoDiarioVagao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fechamento_diario_vagao }
    end
  end

  # GET /fechamento_diario_vagaos/1/edit
  def edit
    @fechamento_diario_vagao = FechamentoDiarioVagao.find(params[:id])
  end

  # POST /fechamento_diario_vagaos
  # POST /fechamento_diario_vagaos.json
  def create
    @fechamento_diario_vagao = FechamentoDiarioVagao.new(params[:fechamento_diario_vagao])

    respond_to do |format|
      if @fechamento_diario_vagao.save
        format.html { redirect_to @fechamento_diario_vagao, notice: 'Fechamento diário de vagões criado com sucesso.' }
        format.json { render json: @fechamento_diario_vagao, status: :created, location: @fechamento_diario_vagao }
      else
        format.html { render action: "new" }
        format.json { render json: @fechamento_diario_vagao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fechamento_diario_vagaos/1
  # PUT /fechamento_diario_vagaos/1.json
  def update
    @fechamento_diario_vagao = FechamentoDiarioVagao.find(params[:id])

    respond_to do |format|
      if @fechamento_diario_vagao.update_attributes(params[:fechamento_diario_vagao])
        format.html { redirect_to @fechamento_diario_vagao, notice: 'Fechamento diário de vagões atualizado com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fechamento_diario_vagao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fechamento_diario_vagaos/1
  # DELETE /fechamento_diario_vagaos/1.json
  def destroy
    @fechamento_diario_vagao = FechamentoDiarioVagao.find(params[:id])
    respond_to do |format|
      if @fechamento_diario_vagao.composicao_de_vagaos.empty?()
        @fechamento_diario_vagao.destroy
        format.html { redirect_to fechamento_diario_vagaos_url }
        format.json { head :ok }
      else
        format.html { redirect_to @fechamento_diario_vagao, alert: ['ERRO: Não foi possível excluir o fechamento diário de vagões pois 
          existem composições de vagões que pertencem a ele.'] }
      end
    end
  end
end

Sisteminha4/app/helpers/fechamento_diario_vagaos_helper.rb
module FechamentoDiarioVagaosHelper
end

Sisteminha4/app/views/fechamento_diario_vagaos/_form.html.erb
<%= form_for(@fechamento_diario_vagao) do |f| %>
  <% if @fechamento_diario_vagao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fechamento_diario_vagao.errors.count, "erro proíbe") %> este fechamento diário de vagões de ser salvo:</h2>

      <ul>
      <% @fechamento_diario_vagao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :datahora %><br />
    <%= f.text_field :data, :value => formatarDataHora(@fechamento_diario_vagao.data) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Sisteminha4/app/views/fechamento_diario_vagaos/_menu.html.erb
<li>
	<a ><%= link_to 'Incluir Fechamento diário de vagões', new_fechamento_diario_vagao_path %> </a>
</li>
<li>
	<a> <%= link_to 'Listar Fechamentos de vagões', fechamento_diario_vagaos_path %></a>
</li>

Sisteminha4/app/views/fechamento_diario_vagaos/edit.html.erb
<%= render 'fechamento_diario_vagaos/menu'%>
<%= render 'layouts/final_menu' %> 
<h1>Editar fechamento diário de vagões</h1>

<%= render 'form' %>

Sisteminha4/app/views/fechamento_diario_vagaos/index.html.erb
<%= render 'fechamento_diario_vagaos/menu'%>
<%= render 'layouts/final_menu' %>
<h1>Fechamentos diários de vagões</h1>

<br>
<table cellpadding="0" cellspacing="0" border="0" class="display dataTable" >
	<thead>
		<tr>
			<th>Link</th>
			<th>Data</th>
			<th>Produto</th>
			<th>Quant.</th>
			<th>Total</th>
			<th>Finalizado?</th>
		</tr>
	</thead>
	<tbody>
		<% @fechamento_diario_vagaos.sort_by{|fechamento_diario_vagao| [fechamento_diario_vagao.data]}.reverse.each do |fechamento_diario_vagao| %>
		<tr>
			<td><%= link_to :ver, fechamento_diario_vagao %></td>
			<td><%= formatarDataHora(fechamento_diario_vagao.data) %></td>
			<td><%= fechamento_diario_vagao.produto %></td>
			<td><%= fechamento_diario_vagao.qtdOperacoes %></td>
			<td><%= fechamento_diario_vagao.pesoTotal %></td>
			<td>
				<% if fechamento_diario_vagao.composicoesFinalizado? %>
				sim
				<% else %>
				não
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<br>

Sisteminha4/app/views/fechamento_diario_vagaos/new.html.erb
<%= render 'fechamento_diario_vagaos/menu'%>
<%= render 'layouts/final_menu' %> 
<h1>Novo fechamento diário de vagões</h1>

<%= render 'form' %>

Sisteminha4/app/views/fechamento_diario_vagaos/show.html.erb
<%= render 'fechamento_diario_vagaos/menu'%>
<%= render 'layouts/final_menu' %> 
<%= render 'layouts/notificacoes' %> 
<p>
	<b>Número:</b>
	<%= @fechamento_diario_vagao.id %>
</p>
<p>
	<b>Data:</b>
	<%= formatarDataHora(@fechamento_diario_vagao.data) %>
</p>
<%= link_to 'Editar', edit_fechamento_diario_vagao_path(@fechamento_diario_vagao) %>
<%= link_to 'Deletar', @fechamento_diario_vagao, confirm: 'Você tem certeza?', method: :delete %>
<br/>
<br/>
<br/>
<% @composicao_de_vagaos = @fechamento_diario_vagao.composicao_de_vagaos %>
<%= render 'composicao_de_vagaos/part_index'%>
<p>
	<b>Total:</b>
	<%= @fechamento_diario_vagao.pesoTotal %>
</p>
<p>
	<b>Quantidade de vagões:</b>
	<%= @fechamento_diario_vagao.qtdOperacoes %>
</p>

<br/>
<br/>
<h1>Nova composição de vagões</h1>
<% @composicao_de_vagao = ComposicaoDeVagao.new(:fechamento_diario_vagao_id => @fechamento_diario_vagao.id) %>
<%= render 'composicao_de_vagaos/form'%>