Sisteminha4/config/routes.rb
Sisteminha2::Application.routes.draw do

  root :to => 'static#index'
  
  
  get 'static/:id' => 'static#static', :as => :static
  
  
  match '/nota_vt/incluir_operacoes_com_vagoes', :controller => 'nota_vts', :action => :incluirOperacoesComVagoes
  
  match '/composicao_de_vagao/atualizar_vagao_carregado', :controller => 'composicao_de_vagaos', :action => :atualizarVagaoCarregado
  
  match '/composicao_de_vagao/atualizar_vagoes_carregados', :controller => 'composicao_de_vagaos', :action => :atualizarVagoesCarregados
  
  match '/composicao_de_vagao/aceitar_atualizacao_vagoes_carregados', :controller => 'composicao_de_vagaos', :action => :atualizacaoVagoesCarregadosAceita
  
  
  match 'relatorios/gerar_relatorio_de_amostras', :controller => :relatorios, :action => :gerarRelatorioAmostras
  
  match 'relatorios/gerar_relatorio_tempos_composicoes_vagoes', :controller => :relatorios, :action => :gerar_relatorio_tempos_composicoes_vagoes
  
  match 'relatorios/gerar_relatorio_fechamento_diario_vagoes', :controller => :relatorios, :action => :gerar_relatorio_fechamento_diario_vagoes
  
  match 'relatorios', :controller => :relatorios, :action => :index
  
  match 'menu_vt', :controller => :vts, :action => :menu_vt
  
  match 'amostras_navio/new', :controller => :amostras_navio, :action => :new
  
  match 'amostras_navio/create', :controller => :amostras_navio, :action => :create
  
  match 'buscar_amostras', :controller => :amostras, :action => :index
  
  match 'buscar_operacoes_com_vagoes', :controller => :operacao_com_vagaos, :action => :index
  
  match '/buscar_notas_de_vts', :controller => :nota_vts, :action => :index
  
  match '/conjunto_operacoes_de_vagoes/create', :controller => :conjunto_operacoes_de_vagoes, :action => :create
  
  match '/conjunto_operacoes_de_vagoes/confirmar_produto', :controller => :conjunto_operacoes_de_vagoes, :action => :confirmarProduto
  
  match '/conjunto_operacoes_de_vagoes/atualizar_operacoes', :controller => :conjunto_operacoes_de_vagoes, :action => :atualizarOperacoes
  
  match '/conjunto_operacoes_de_vagoes/confirmar_atualizacao_operacoes', :controller => :conjunto_operacoes_de_vagoes, :action => :confirmarAtualizacaoOperacoes

  match '/operacao_com_vagao/limpar_composicao', :controller => :operacao_com_vagaos, :action => :limparComposicao
  
  resources :fechamento_diario_vagaos

  resources :composicao_de_vagaos

  resources :lacres

  resources :solicitacaos

  resources :vts

  resources :vistorias

  resources :usuarios

  resources :tipo_amostras

  resources :produto_vts

  resources :produtos

  resources :problemas

  resources :origems

  resources :operacao_com_vagaos

  resources :operacaos

  resources :nota_vts

  resources :grupo_usuarios

  resources :finalidades

  resources :amostras
  
  get ":id" => "static#static", :as => :static

end

Sisteminha4/app/models/produto.rb
class Produto < ActiveRecord::Base
  
  validates :nome_completo, :uniqueness => { :case_sensitive => false }, :presence => true
  validates :nome_curto, :uniqueness => { :case_sensitive => false }, :presence => true
  validates :codigo, :uniqueness => { :case_sensitive => false }, :presence => true
      
  has_many :amostras
  has_many :produto_vts, :foreign_key => :descricao_produto_id
  
      
  def descricaoCompleta
    descricao = "#{self.codigo} | "
    descricao << "#{self.nome_curto} | "
    descricao << self.nome_completo
    descricao
  end
  
  def temBenzeno?
    if [1,2,3,34,35,36,41,42,43,51,55].include?(id)
      true
    else
      false
    end
  end
  
end

Sisteminha4/app/controllers/produtos_controller.rb
# encoding: utf-8
class ProdutosController < ApplicationController
  
  before_filter :liberarAcesso, :except => [:index, :show, :new]
  def liberarAcesso
    if @usuario.privilegio.id == 1
    return true
    else
      redirect_to "/static/grupo_diferente"
    return false
    end
  end
  
  
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com sucesso.' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, notice: 'Produto atualizada com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    respond_to do |format|
      erros = []
      if @produto.amostras.empty?() and
        @produto.produto_vts.empty?()

        @produto.destroy
        format.html { redirect_to produtos_url }
        format.json { head :ok }
      end
      if !@produto.amostras.empty?()
        erros << "ERRO: Não foi possível excluir o produto pois existem amostras que utilizam ele."
      end
      if !@produto.produto_vts.empty?()
        erros << "ERRO: Não foi possível excluir o produto pois existem produtos de vagões que utilizam ele."
      end
      if erros != []
         format.html { redirect_to @produto, alert: erros }
      end
    end
  end
end

Sisteminha4/app/helpers/produtos_helper.rb
module ProdutosHelper
end

Sisteminha4/app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "erro proíbe") %> este produto de ser salvo:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :codigo, "Código" %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nome_curto %><br />
    <%= f.text_field :nome_curto %>
  </div>
  <div class="field">
    <%= f.label :nome_completo %><br />
    <%= f.text_field :nome_completo %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Sisteminha4/app/views/produtos/_menu.html.erb
<li>
	<a > <%= link_to 'Incluir Produto', new_produto_path %> </a>
</li>
<li>
	<a> <%= link_to 'Listar Produtos', produtos_path %></a>
</li>

Sisteminha4/app/views/produtos/edit.html.erb
<%= render 'produtos/menu' %>
<%= render 'layouts/final_menu' %> 
<h1>Editar produto</h1>

<%= render 'form' %>

Sisteminha4/app/views/produtos/index.html.erb
<%= render 'produtos/menu'%>
<%= render 'layouts/final_menu' %>
<h1>Produtos</h1>

<br>
<table cellpadding="0" cellspacing="0" border="0" class="display dataTable" >
	<thead>
		<tr>
			<th>Número</th>
			<th>Código</th>
			<th>Nome curto</th>
			<th>Nome completo</th>
		</tr>
	</thead>
	<tbody>
		<% @produtos.each do |produto| %>
		<tr>
			<td><%= link_to produto.id, produto %></td>
			<td><%= produto.codigo %></td>
			<td><%= produto.nome_curto %></td>
			<td><%= produto.nome_completo %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<br>

Sisteminha4/app/views/produtos/new.html.erb
<%= render 'produtos/menu' %>
<%= render 'layouts/final_menu' %> 
<h1>Novo produto</h1>

<%= render 'form' %>

Sisteminha4/app/views/produtos/show.html.erb
<%= render 'produtos/menu' %>
<%= render 'layouts/final_menu' %>
<%= render 'layouts/notificacoes' %>

<p>
	<b>Código:</b>
	<%= @produto.codigo %>
</p>
<p>
	<b>Nome curto:</b>
	<%= @produto.nome_curto %>
</p>
<p>
	<b>Nome completo:</b>
	<%= @produto.nome_completo %>
</p>
<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Deletar', @produto, confirm: 'Você tem certeza?', method: :delete %> 