Sisteminha4/config/routes.rb
Sisteminha2::Application.routes.draw do

  root :to => 'static#index'
  
  
  get 'static/:id' => 'static#static', :as => :static
  
  
  match '/nota_vt/incluir_operacoes_com_vagoes', :controller => 'nota_vts', :action => :incluirOperacoesComVagoes
  
  match '/composicao_de_vagao/atualizar_vagao_carregado', :controller => 'composicao_de_vagaos', :action => :atualizarVagaoCarregado
  
  match '/composicao_de_vagao/atualizar_vagoes_carregados', :controller => 'composicao_de_vagaos', :action => :atualizarVagoesCarregados
  
  match '/composicao_de_vagao/aceitar_atualizacao_vagoes_carregados', :controller => 'composicao_de_vagaos', :action => :atualizacaoVagoesCarregadosAceita
  
  
  match 'relatorios/gerar_relatorio_de_amostras', :controller => :relatorios, :action => :gerarRelatorioAmostras
  
  match 'relatorios/gerar_relatorio_tempos_composicoes_vagoes', :controller => :relatorios, :action => :gerar_relatorio_tempos_composicoes_vagoes
  
  match 'relatorios/gerar_relatorio_fechamento_diario_vagoes', :controller => :relatorios, :action => :gerar_relatorio_fechamento_diario_vagoes
  
  match 'relatorios', :controller => :relatorios, :action => :index
  
  match 'menu_vt', :controller => :vts, :action => :menu_vt
  
  match 'amostras_navio/new', :controller => :amostras_navio, :action => :new
  
  match 'amostras_navio/create', :controller => :amostras_navio, :action => :create
  
  match 'buscar_amostras', :controller => :amostras, :action => :index
  
  match 'buscar_operacoes_com_vagoes', :controller => :operacao_com_vagaos, :action => :index
  
  match '/buscar_notas_de_vts', :controller => :nota_vts, :action => :index
  
  match '/conjunto_operacoes_de_vagoes/create', :controller => :conjunto_operacoes_de_vagoes, :action => :create
  
  match '/conjunto_operacoes_de_vagoes/confirmar_produto', :controller => :conjunto_operacoes_de_vagoes, :action => :confirmarProduto
  
  match '/conjunto_operacoes_de_vagoes/atualizar_operacoes', :controller => :conjunto_operacoes_de_vagoes, :action => :atualizarOperacoes
  
  match '/conjunto_operacoes_de_vagoes/confirmar_atualizacao_operacoes', :controller => :conjunto_operacoes_de_vagoes, :action => :confirmarAtualizacaoOperacoes

  match '/operacao_com_vagao/limpar_composicao', :controller => :operacao_com_vagaos, :action => :limparComposicao
  
  resources :fechamento_diario_vagaos

  resources :composicao_de_vagaos

  resources :lacres

  resources :solicitacaos

  resources :vts

  resources :vistorias

  resources :usuarios

  resources :tipo_amostras

  resources :produto_vts

  resources :produtos

  resources :problemas

  resources :origems

  resources :operacao_com_vagaos

  resources :operacaos

  resources :nota_vts

  resources :grupo_usuarios

  resources :finalidades

  resources :amostras
  
  get ":id" => "static#static", :as => :static

end

Sisteminha4/app/models/operacao.rb
class Operacao < ActiveRecord::Base
  
  validates :descricao, :uniqueness => { :case_sensitive => false }, :presence => true
  
  has_many :amostras
end

Sisteminha4/app/controllers/operacaos_controller.rb
# encoding: utf-8
class OperacaosController < ApplicationController
  
  before_filter :liberarAcesso, :except => [:index, :show, :new]
  def liberarAcesso
    if @usuario.privilegio.id == 1
    return true
    else
      redirect_to "/static/grupo_diferente"
    return false
    end
  end
  
  
  # GET /operacaos
  # GET /operacaos.json
  def index
    @operacaos = Operacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @operacaos }
    end
  end

  # GET /operacaos/1
  # GET /operacaos/1.json
  def show
    @operacao = Operacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operacao }
    end
  end

  # GET /operacaos/new
  # GET /operacaos/new.json
  def new
    @operacao = Operacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operacao }
    end
  end

  # GET /operacaos/1/edit
  def edit
    @operacao = Operacao.find(params[:id])
  end

  # POST /operacaos
  # POST /operacaos.json
  def create
    @operacao = Operacao.new(params[:operacao])

    respond_to do |format|
      if @operacao.save
        format.html { redirect_to @operacao, notice: 'Operação criada com sucesso.' }
        format.json { render json: @operacao, status: :created, location: @operacao }
      else
        format.html { render action: "new" }
        format.json { render json: @operacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /operacaos/1
  # PUT /operacaos/1.json
  def update
    @operacao = Operacao.find(params[:id])

    respond_to do |format|
      if @operacao.update_attributes(params[:operacao])
        format.html { redirect_to @operacao, notice: 'Operação atualizada com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @operacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operacaos/1
  # DELETE /operacaos/1.json
  def destroy
    @operacao = Operacao.find(params[:id])

    respond_to do |format|
      if @operacao.amostras.empty?()
        @operacao.destroy
        format.html { redirect_to operacaos_url }
        format.json { head :ok }
      else
        format.html { redirect_to @operacao, alert: ['ERRO: Não foi possível excluir a operação pois existem amostras que utilizam ela.'] }
      end
    end
  end
end

Sisteminha4/app/helpers/operacaos_helper.rb
module OperacaosHelper
end

Sisteminha4/app/views/operacaos/_form.html.erb
<%= form_for(@operacao) do |f| %>
  <% if @operacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operacao.errors.count, "erro proíbe") %> esta operação de ser salva:</h2>

      <ul>
      <% @operacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Sisteminha4/app/views/operacaos/_menu.html.erb
<li>
	<a > <%= link_to 'Incluir Operação', new_operacao_path %> </a>
</li>
<li>
	<a> <%= link_to 'Listar Operações', operacaos_path %></a>
</li>

Sisteminha4/app/views/operacaos/edit.html.erb
<%= render 'operacaos/menu' %>
<%= render 'layouts/final_menu' %> 
<h1>Editar operação</h1>

<%= render 'form' %>

Sisteminha4/app/views/operacaos/index.html.erb
<%= render 'operacaos/menu' %>
<%= render 'layouts/final_menu' %>
<h1>Operacões</h1>

<br>
<table cellpadding="0" cellspacing="0" border="0" class="display dataTable" >
	<thead>
		<tr>
			<th>Número</th>
			<th>Descrição</th>
		</tr>
	</thead>
	<tbody>
		<% @operacaos.each do |operacao| %>
		<tr>
			<td><%= link_to operacao.id, operacao %></td>
			<td><%= operacao.descricao %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<br>

Sisteminha4/app/views/operacaos/new.html.erb
<%= render 'operacaos/menu' %>
<%= render 'layouts/final_menu' %> 
<h1>Nova operação</h1>

<%= render 'form' %>

Sisteminha4/app/views/operacaos/show.html.erb
<%= render 'operacaos/menu' %>
<%= render 'layouts/final_menu' %> 
<%= render 'layouts/notificacoes' %>

<p>
  <b>Descrição:</b>
  <%= @operacao.descricao %>
</p>


<%= link_to 'Editar', edit_operacao_path(@operacao) %>
<%= link_to 'Deletar', @operacao, confirm: 'Você tem certeza?', method: :delete %>